name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: ["**"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Linter
              run: pnpm run lint
              continue-on-error: true
            - name: Build packages
              run: pnpm run build
            - name: Run tests
              run: |
                  pnpm dev &
                  pnpm run test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: genauigkeit-report
                  path: |
                      v2/pink-sb/.genauigkeit/report/index.html
                      v2/pink-sb/.genauigkeit/diffs/
                  retention-days: 30
